// <auto-generated />
using System;
using CourseWorkFactoryAutomatization.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CourseWorkFactoryAutomatization.Migrations
{
    [DbContext(typeof(CourseWorkContext))]
    [Migration("20230107074033_SetDetaCreate")]
    partial class SetDetaCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountantDetailCatalog", b =>
                {
                    b.Property<long>("AccountantsId")
                        .HasColumnType("bigint");

                    b.Property<long>("DetailCatalogsId")
                        .HasColumnType("bigint");

                    b.HasKey("AccountantsId", "DetailCatalogsId");

                    b.HasIndex("DetailCatalogsId");

                    b.ToTable("AccountantDetailCatalog");
                });

            modelBuilder.Entity("CourseWorkFactoryAutomatization.Models.Detail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<long>("DetailCatalogId")
                        .HasColumnType("bigint");

                    b.Property<long>("TechnicId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DetailCatalogId");

                    b.HasIndex("TechnicId");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("CourseWorkFactoryAutomatization.Models.DetailCatalog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("DetailCatalogs");
                });

            modelBuilder.Entity("CourseWorkFactoryAutomatization.Models.Technic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("TechnicManualId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TechnicManualId");

                    b.ToTable("Technics");
                });

            modelBuilder.Entity("CourseWorkFactoryAutomatization.Models.TechnicManual", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("TechnicManuals");
                });

            modelBuilder.Entity("CourseWorkFactoryAutomatization.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserCatalogId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserCatalogId1");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CourseWorkFactoryAutomatization.Models.UserCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("UserCatalogs");
                });

            modelBuilder.Entity("SuperVisorTechnicManual", b =>
                {
                    b.Property<long>("SuperVisorsId")
                        .HasColumnType("bigint");

                    b.Property<long>("TechnicManualsId")
                        .HasColumnType("bigint");

                    b.HasKey("SuperVisorsId", "TechnicManualsId");

                    b.HasIndex("TechnicManualsId");

                    b.ToTable("SuperVisorTechnicManual");
                });

            modelBuilder.Entity("CourseWorkFactoryAutomatization.Models.Accountant", b =>
                {
                    b.HasBaseType("CourseWorkFactoryAutomatization.Models.User");

                    b.HasDiscriminator().HasValue("Accountant");
                });

            modelBuilder.Entity("CourseWorkFactoryAutomatization.Models.Admin", b =>
                {
                    b.HasBaseType("CourseWorkFactoryAutomatization.Models.User");

                    b.Property<long>("IdCatalog")
                        .HasColumnType("bigint");

                    b.Property<int?>("UserCatalogId")
                        .HasColumnType("integer");

                    b.HasIndex("UserCatalogId");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("CourseWorkFactoryAutomatization.Models.SuperVisor", b =>
                {
                    b.HasBaseType("CourseWorkFactoryAutomatization.Models.User");

                    b.HasDiscriminator().HasValue("SuperVisor");
                });

            modelBuilder.Entity("AccountantDetailCatalog", b =>
                {
                    b.HasOne("CourseWorkFactoryAutomatization.Models.Accountant", null)
                        .WithMany()
                        .HasForeignKey("AccountantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseWorkFactoryAutomatization.Models.DetailCatalog", null)
                        .WithMany()
                        .HasForeignKey("DetailCatalogsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseWorkFactoryAutomatization.Models.Detail", b =>
                {
                    b.HasOne("CourseWorkFactoryAutomatization.Models.DetailCatalog", "DetailCatalog")
                        .WithMany("Details")
                        .HasForeignKey("DetailCatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseWorkFactoryAutomatization.Models.Technic", "Technic")
                        .WithMany("Details")
                        .HasForeignKey("TechnicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetailCatalog");

                    b.Navigation("Technic");
                });

            modelBuilder.Entity("CourseWorkFactoryAutomatization.Models.Technic", b =>
                {
                    b.HasOne("CourseWorkFactoryAutomatization.Models.TechnicManual", "TechnicManual")
                        .WithMany("Technics")
                        .HasForeignKey("TechnicManualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TechnicManual");
                });

            modelBuilder.Entity("CourseWorkFactoryAutomatization.Models.User", b =>
                {
                    b.HasOne("CourseWorkFactoryAutomatization.Models.UserCatalog", null)
                        .WithMany("Users")
                        .HasForeignKey("UserCatalogId1");
                });

            modelBuilder.Entity("SuperVisorTechnicManual", b =>
                {
                    b.HasOne("CourseWorkFactoryAutomatization.Models.SuperVisor", null)
                        .WithMany()
                        .HasForeignKey("SuperVisorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseWorkFactoryAutomatization.Models.TechnicManual", null)
                        .WithMany()
                        .HasForeignKey("TechnicManualsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseWorkFactoryAutomatization.Models.Admin", b =>
                {
                    b.HasOne("CourseWorkFactoryAutomatization.Models.UserCatalog", "UserCatalog")
                        .WithMany("Admins")
                        .HasForeignKey("UserCatalogId");

                    b.Navigation("UserCatalog");
                });

            modelBuilder.Entity("CourseWorkFactoryAutomatization.Models.DetailCatalog", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("CourseWorkFactoryAutomatization.Models.Technic", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("CourseWorkFactoryAutomatization.Models.TechnicManual", b =>
                {
                    b.Navigation("Technics");
                });

            modelBuilder.Entity("CourseWorkFactoryAutomatization.Models.UserCatalog", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
